function(v8_cmake_platform out_os out_cpu)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(os linux)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    set(os mac)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(os win)
  else()
    message(FATAL_ERROR "V8: unsupported system '${CMAKE_SYSTEM_NAME}'")
  endif()
  set(cpu "${CMAKE_SYSTEM_PROCESSOR}")
  if(os STREQUAL "mac" AND CMAKE_OSX_ARCHITECTURES)
    list(LENGTH CMAKE_OSX_ARCHITECTURES count)
    if(NOT count EQUAL 1)
      message(FATAL_ERROR "V8: universal builds require separate build trees per architecture")
    endif()
    set(cpu "${CMAKE_OSX_ARCHITECTURES}")
  elseif(os STREQUAL "win" AND CMAKE_GENERATOR_PLATFORM)
    set(cpu "${CMAKE_GENERATOR_PLATFORM}")
  endif()
  string(TOLOWER "${cpu}" cpu)
  if(cpu MATCHES "^(x86_64|amd64|x64)$")
    set(cpu x64)
  elseif(cpu MATCHES "^(aarch64|arm64)$")
    set(cpu arm64)
  else()
    message(FATAL_ERROR "V8: unsupported architecture '${cpu}'; supported: x64, arm64")
  endif()
  if(os STREQUAL "win" AND (NOT cpu STREQUAL "x64" OR NOT MSVC))
    message(FATAL_ERROR "V8: Windows requires an x64 MSVC-compatible toolchain")
  endif()
  if(DEFINED CMAKE_SIZEOF_VOID_P AND NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "V8: the consumer compiler must target 64 bits")
  endif()
  if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL CMAKE_SYSTEM_NAME)
    message(FATAL_ERROR "V8: cross-OS compilation is not supported")
  endif()
  if(os STREQUAL "linux" AND CMAKE_CROSSCOMPILING AND NOT CMAKE_SYSROOT)
    message(FATAL_ERROR "V8: Linux cross-compilation requires CMAKE_SYSROOT")
  endif()
  if(os STREQUAL "linux" AND NOT CMAKE_HOST_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64|x64)$")
    message(FATAL_ERROR "V8: the pinned Linux LLVM tools require an x64 host; cross-compile arm64 with cmake/toolchains/linux-arm64.cmake")
  endif()
  set(${out_os} "${os}" PARENT_SCOPE)
  set(${out_cpu} "${cpu}" PARENT_SCOPE)
endfunction()
